help:
  help_tutorial: "http://www.railstutorial.org/help"
  help_book: "http://www.railstutorial.org/book"
home:
  home_tutorial: "http://www.railstutorial.org/"
user:
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  max_name: 50
  max_email: 255
  min_password: 6
  gravatar_size: 50
  deadline_expiration: 2
users:
  gravatar_size: 30
footer:
  footer_link: "https://www.railstutorial.org/"
  footer_link2: "https://www.michaelhartl.com/"
  footer_link3: "https://news.railstutorial.org/"
users_helper:
  gravatar_size: 80
edit:
  link: "https://gravatar.com/emails"
index:
  items: 10
micropost:
  max_length_content: 140
  image_path: <% %w(image/jpeg image/gif image/png) %>
  accept_path: "image/jpeg,image/gif,image/png"
  max_data: 5
  max_size: [500, 500]
  gravatar_size: 50
